# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [6]:
pip install generators


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for generators: filename=generators-2020.4.27-py3-none-any.whl size=42868 sha256=e1d2b66cb0eabf28d67241aa24011e24c2440681e623ab1e6976ea1fa80655ac
  Stored in directory: c:\users\pavan\appdata\local\pip\cache\wheels\e3\ab\13\05a7554f7914b57f2326107ad2ea6fd51d523369b261601021
  Created wheel for strict_functions: filename=strict_functions-2020.2.4-py3-none-any.whl size=15463 sha256=855aa740759b14bf71032775d312ab1b82ca6d4da39dd17da26b30d609e2b751
  Stored in directory: c:\users\pavan\appdata\local\pip\cache\wheels\d6\79\73\c1f0a48f707f26ec569b6e3b27d1bc6f76caca8a7fa0a456e3
Successfully built generators strict_functions


In [7]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
np.__version__

'1.23.5'

In [12]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pavan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pavan/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pavan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/pavan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/pavan/anaconda3\\Lib

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10).shape

(10,)

#### 4. How to find the memory size of any array (★☆☆)

In [19]:
#nbytes - gives array size in bytes
np.zeros(10).nbytes


80

In [20]:
#size in kilobytes
np.zeros(10).nbytes/1024

0.078125

In [22]:
#size in megabytes
(np.zeros(10).nbytes/1024)/1024

7.62939453125e-05

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [23]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [25]:
#command to run from command line
#python -c "import numpy as np; help(np.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
arr = np.zeros(10)

In [27]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
arr[4]=1

In [29]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [34]:
arr1 = np.arange(10,50)

In [35]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
arr2 = arr1[::-1]

In [45]:
arr2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [47]:
arr3 = np.arange(0,9)

In [49]:
arr3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [50]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
np.random.rand(3,3,3)

array([[[0.33430645, 0.8874784 , 0.13989498],
        [0.85502643, 0.26041346, 0.78464369],
        [0.08917656, 0.86633093, 0.35765732]],

       [[0.96159382, 0.73460283, 0.58987018],
        [0.16411727, 0.54042291, 0.09512081],
        [0.75281725, 0.1578372 , 0.46381586]],

       [[0.59375123, 0.85659046, 0.92756113],
        [0.6943513 , 0.50933152, 0.07791652],
        [0.222736  , 0.22980998, 0.69595414]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
arr = np.random.rand(10,10)

In [55]:
arr

array([[0.46017858, 0.56898121, 0.98211856, 0.10894534, 0.82648127,
        0.52063251, 0.79046462, 0.86851678, 0.50499685, 0.64752079],
       [0.99898018, 0.97230285, 0.39065818, 0.92278132, 0.85774859,
        0.84051529, 0.24367313, 0.28840888, 0.89756435, 0.75208689],
       [0.49208481, 0.1755984 , 0.71705873, 0.06545809, 0.35783724,
        0.22743045, 0.72743741, 0.3660894 , 0.50557002, 0.83805846],
       [0.72906163, 0.87115825, 0.75944997, 0.61141422, 0.7143224 ,
        0.90220224, 0.10764028, 0.76861456, 0.40362275, 0.77461672],
       [0.32129152, 0.45860331, 0.45210618, 0.74751583, 0.92969029,
        0.77163313, 0.40085529, 0.23102235, 0.2477607 , 0.06788905],
       [0.42662829, 0.38653764, 0.32739211, 0.22338087, 0.69470176,
        0.83452225, 0.52887409, 0.63136069, 0.02105207, 0.77846279],
       [0.82453794, 0.42893783, 0.75695664, 0.63278578, 0.06384806,
        0.77669705, 0.7712886 , 0.07472212, 0.98305272, 0.67185932],
       [0.53348705, 0.485935  , 0.2480692

In [56]:
arr.min()

0.004746749715828558

In [57]:
arr.max()

0.9989801790300278

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [60]:
arr = np.random.rand(30)

In [61]:
arr

array([0.43360718, 0.91277345, 0.20888916, 0.25994603, 0.2703461 ,
       0.72371822, 0.51232148, 0.63769347, 0.51332482, 0.39922399,
       0.92230366, 0.30116452, 0.38997213, 0.74826719, 0.93269233,
       0.97349751, 0.97424738, 0.66696492, 0.03494455, 0.28290603,
       0.337006  , 0.40821047, 0.72570816, 0.22194999, 0.29111315,
       0.57794734, 0.50428928, 0.36586492, 0.71988757, 0.4080366 ])

In [62]:
arr.mean()

0.5219605874184948

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [94]:
arr = np.ones((5,5))

In [95]:
arr[1:-1,1:-1] = 0

In [96]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [99]:
rows,cols = arr.shape

In [103]:
arr.dtype

dtype('float64')

In [104]:
arr1 = np.zeros((rows+2,cols+2),dtype = arr.dtype)

In [108]:
arr1[1:-1,1:-1] = arr

In [109]:
arr1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan  ---> nan
np.nan == np.nan --> False
np.inf > np.nan --> False
np.nan - np.nan --> np.nan
np.nan in set([np.nan]) --> True
0.3 == 3 * 0.1 --> false
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [128]:
arr = np.zeros((5,5))

In [132]:
np.fill_diagonal(arr[1:],[1,2,3,4])

In [133]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [140]:
arr = np.zeros((8,8))

In [141]:
arr[1::2, ::2] = 1
arr[::2,1::2] = 1

In [142]:
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [145]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [149]:
def tile(n):
    arr = np.zeros((n,n))
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    return arr
    

In [169]:
print(tile(8).ndim)

2


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [152]:
arr = np.random.rand(5,5)

In [153]:
arr

array([[0.28525771, 0.32921681, 0.13749976, 0.51017571, 0.27543321],
       [0.0390583 , 0.36147016, 0.43491688, 0.84600833, 0.98750638],
       [0.66131127, 0.68356049, 0.89496913, 0.35203294, 0.6806908 ],
       [0.8079451 , 0.05009945, 0.48206873, 0.18162623, 0.88978006],
       [0.2967726 , 0.01592514, 0.92109007, 0.6393776 , 0.03011302]])

In [159]:
normalised_matrix = (arr - np.mean(arr))/np.std(arr)

In [160]:
normalised_matrix

array([[-0.60896065, -0.46542407, -1.09142438,  0.12544845, -0.6410399 ],
       [-1.41285844, -0.36010944, -0.12028898,  1.2220193 ,  1.68404304],
       [ 0.61894085,  0.69158967,  1.3818876 , -0.39092415,  0.68221948],
       [ 1.09773407, -1.37680653,  0.03367269, -0.94734129,  1.36494407],
       [-0.57136186, -1.48839354,  1.46717847,  0.54732237, -1.44206682]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [164]:
color = np.dtype([("r",np.ubyte),
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [166]:
arr1 = np.ones((5,3))

In [168]:
arr2 = np.ones((3,2))

In [ ]:
for num in arr1[]

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)