In [1]:
num1 = 10
num2 = 2.5
name = "pavani"

In [2]:
print("The value of num1 is:", num1)

The value of num1 is: 10


In [3]:
print("The value of num2 is:", num2)

The value of num2 is: 2.5


In [4]:
print("The value of name is:", name)

The value of name is: pavani


In [6]:
print("The type of num1 is:", type(num1))

The type of num1 is: <class 'int'>


In [7]:
print("The type of name is:", type(name))

The type of name is: <class 'str'>


In [8]:
res1 = num1 + num2

In [9]:
print("Sum of num1 & num2 is", res1)

Sum of num1 & num2 is 12.5


In [11]:
print(f'Sum of {num1} & {num2} is: {res1}')

Sum of 10 & 2.5 is: 12.5


In [12]:
print(name[0])

p


In [14]:
print(name[0:2])

pa


In [15]:
print(name[-1])

i


[::2]: This is the slicing syntax used on the string. 
It consists of three parts: 

start:stop:step

1. start is not specified, so it defaults to the beginning of the string.

2. stop is not specified, so it defaults to the end of the string.

3. step is specified as 2, which means it selects every second character from the string, starting from the beginning.

In [17]:
#access alternate characters
print(name[::2])

pa


In [18]:
print(name[::])

pavani


In [19]:
age = 15

if age < 18:
    print("Minor")

Minor


In [21]:
age = 35

#since condition is failed it prints nothing
if age < 18:
    print("Minor")
else:
    print("Major")

Major


In [23]:
i = 20

if i == 10:
    print("i is 10")
    
elif i ==15:
    print("i is 15")

elif i == 20:
    print("i is 20")

else:
    print("i is not present") 
    

i is 20


In [2]:
##Advanced data types
#list
list_num1 = [78,44,11,99,22] #homogenous list
list_num2 = [78,44,11,99,22,"sai"] # heterogenous list
list_num3 = [78,44,11,99,22,"sai", ['bye', 77, 6]] #listed list
type(list_num1)

list

In [3]:
list_num1

[78, 44, 11, 99, 22]

In [7]:
print(list_num1[0:2])
print(list_num1[3:])
print(list_num2[5][1])
print(list_num2[-3])
print(list_num3[-1][1])
print(list_num1[::2])
print(list_num3[-1][0][1])

[78, 44]
[99, 22]
a
99
77
[78, 11, 22]
y


In [8]:
#set
set_num = {78,44,11,99,22}
type(set_num)

set

In [9]:
#tuple
#immutable i.e., we cant change the existing value of tuple or add a new value
tuple_num = (78,44,11,99,22)
type(tuple_num)

tuple

In [13]:
#dictionary

d1 = {"name":"pavani","age":28, "num_list":[6,8,4,9]}
print(d1)
print(type(d1))

{'name': 'pavani', 'age': 28, 'num_list': [6, 8, 4, 9]}
<class 'dict'>


In [14]:
print(d1['name'])

pavani


In [15]:
print(d1['num_list'][2])

4


In [16]:
##Loops

S = "Hello World"
for i in S:
    print(i)

H
e
l
l
o
 
W
o
r
l
d


In [2]:
i = list(range(0,10))
i

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [19]:
for i in range(0,12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [20]:
#while

count = 0 
while(count<3):
    print("hello")
    count = count + 1

hello
hello
hello


In [21]:
i=1
while(i<=10):
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [22]:
#pass - iterates over the loop
l=[1,2,3]
for i in l:
    pass

In [24]:
#continue - returns control to the beginning of the loop

i=0
a="HelloWorld"

while i < len(a):
    if a[i] == 'H' or a[i] == 'W':
        i=i+1
        continue

    print(a[i]);
    i=i+1

e
l
l
o
o
r
l
d


In [25]:
#break - comes out of the loop
i=0
a="HelloWorld"

while i < len(a):
    if a[i] == 'H' or a[i] == 'W':
        i=i+1
        break

    print(a[i]);
    i=i+1

In [26]:
#functions

#without arguments

def square():
    num1 = int(input("Enter a number:"))
    res = num1 * num1
    print("Square of the number:", res)

In [27]:
square()

Enter a number:4
Square of the number: 16


In [30]:
#with arguments
def square(num):
    res = num * num
    print("Square of the number:", res)

In [31]:
num1 = int(input("Enter a number:"))
square(num1)

Enter a number:5
Square of the number: 25


In [32]:
#function with return statement

def square(num):
    res = num * num
    return res

In [33]:
num1 = int(input("Enter a number:"))
result = square(num1)
print("Square of the number:", result)

Enter a number:9
Square of the number: 81


In [36]:
def arithematic(num1, num2):
    sum = num1 + num2
    diff = num1 - num2
    product = num1 * num2
    quotient = num1 / num2
    return sum, diff, product, quotient

In [37]:
num1 = int(input("Enter a number:"))
num2 = int(input("Enter a number:"))
a,b,c,d = arithematic(num1, num2)
print(a)
print(b)
print(c)
print(d)

Enter a number:2
Enter a number:3
5
-1
6
0.6666666666666666


In [38]:
#*args **kwargs

def test_function(num1,num2, num3):
    print(num1,num2,num3)

In [39]:
test_function(1,2,3)

1 2 3


In [40]:
test_function(1,2,3,4)

TypeError: test_function() takes 3 positional arguments but 4 were given

In [41]:
def test_function(*args):
    print(args)
    print(type(args))

In [42]:
test_function(1,2,3,4)

(1, 2, 3, 4)
<class 'tuple'>


In [43]:
test_function(1,2,3)

(1, 2, 3)
<class 'tuple'>


In [44]:
# **args - accepts (key, value) pairs
def test_function(**kwargs):
    print(kwargs)
    print(type(kwargs))

In [45]:
test_function(first = "pavani", last = 'billapati')

{'first': 'pavani', 'last': 'billapati'}
<class 'dict'>


In [46]:
test_function(first = "pavani")

{'first': 'pavani'}
<class 'dict'>


In [49]:
#class
#init - is called automatically whenever an object is created
#Each object in class definition begins with a reference to instance object.
# It is by convention named self
class Dog:
    def __init__(self, breed):
        self.breed = breed
        
sam = Dog('Lab')
frank = Dog('Huskie')

In [48]:
sam.breed

'Lab'

In [50]:
frank.breed

'Huskie'

In [51]:
class Dog:
    
    #class Object attribute - would be part of all objects created for this class
    species = 'mammal'
    
    def __init__(self, breed, name):
        self.breed = breed
        self.name = name

In [52]:
sam = Dog('Lab','Sam')

In [53]:
sam.name

'Sam'

In [54]:
sam.breed

'Lab'

In [55]:
sam.species

'mammal'

In [56]:
Dog.species

'mammal'

In [18]:
class Circle:
    pi = 3.14
    
    def __init__(self, radius=1):
        self.radius = radius
        self.area = Circle.pi * radius * radius
        
    def setRadius(self,new_radius):
        self.radius = new_radius
        self.area = Circle.pi * self.radius * self.radius
        
    def getCircumference(self):
        return 2 * Circle.pi * self.radius

In [20]:
c = Circle()

In [68]:
print(c.radius)

1


In [71]:
c.area

3.14

In [21]:
c.pi

3.14

In [69]:
c.getCircumference()

6.28

In [78]:
c1 = Circle(2)

In [79]:
c1.radius

2

In [80]:
c1.area

12.56

In [81]:
c1.getCircumference()

12.56

In [82]:
c1.setRadius(3)

In [83]:
c1.radius

3

In [84]:
c1.area

28.259999999999998

In [85]:
c1.getCircumference()

18.84

In [97]:
#Inheritance

class Animal():
    def __init__(self):
        print("Animal created")
        
    def whoAmI(self):
        print("Animal")
        
    def eat(self):
        print("Eating")
        
class Dog(Animal):
    def __init__(self):
        #Animal.__init__(self) # it's not mandate to create base class constructor
        print("Dog created")
        
    def whoAmI(self):
        print("Dog")
        
    def bark(self):
        print("Woof!")

In [98]:
d= Dog()

Dog created


In [99]:
d.whoAmI()

Dog


In [100]:
d.eat()

Eating


### Array Attributes & Methods

In [2]:
import numpy as np

In [3]:
#creates an numpy array that has elements from 25 elements from 0 to 24
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [7]:
arr = np.arange(12,25)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
arr = np.arange(12,25,3)
arr

array([12, 15, 18, 21, 24])

In [11]:
ranarr = np.random.randint(0,50,10) # generates 10(last parameter) integers between 0 to 50 

In [12]:
ranarr

array([34, 23, 42, 37, 30,  7, 15, 24, 46, 43])

In [116]:
ranarr1 = np.random.rand(0,50,10) # incorrect way of assigning
#should specify the shape i.e., the number of elements it has to print
# prints numbers random numbers between 0 to 1

In [117]:
ranarr1

array([], shape=(0, 50, 10), dtype=float64)

In [118]:
np.zeros(3)

array([0., 0., 0.])

In [121]:
z = np.zeros((5,5))

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [123]:
print(z.shape)

(5, 5)


In [124]:
#Creates an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
#linspace - provides an evenly spaced numbers over a specified interval
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [17]:
np.linspace(5,15) # if third argument is missing it generates random number of evenly spaced numbers

array([ 5.        ,  5.20408163,  5.40816327,  5.6122449 ,  5.81632653,
        6.02040816,  6.2244898 ,  6.42857143,  6.63265306,  6.83673469,
        7.04081633,  7.24489796,  7.44897959,  7.65306122,  7.85714286,
        8.06122449,  8.26530612,  8.46938776,  8.67346939,  8.87755102,
        9.08163265,  9.28571429,  9.48979592,  9.69387755,  9.89795918,
       10.10204082, 10.30612245, 10.51020408, 10.71428571, 10.91836735,
       11.12244898, 11.32653061, 11.53061224, 11.73469388, 11.93877551,
       12.14285714, 12.34693878, 12.55102041, 12.75510204, 12.95918367,
       13.16326531, 13.36734694, 13.57142857, 13.7755102 , 13.97959184,
       14.18367347, 14.3877551 , 14.59183673, 14.79591837, 15.        ])

In [126]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [127]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [129]:
#Reshape

arr = np.arange(0,10)

In [130]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
type(arr)

numpy.ndarray

In [132]:
arr.shape

(10,)

In [133]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
ranarr

array([34, 36, 42, 40,  6, 22, 38, 11, 23, 10])

In [135]:
ranarr.max()

42

In [137]:
#index of maximum value
ranarr.argmax()

2

In [138]:
ranarr.min()

6

In [139]:
#index of minimum value
ranarr.argmin()

4

In [140]:
arr.shape

(10,)

In [141]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
arr.reshape(2,5).shape

(2, 5)

In [143]:
arr.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [144]:
arr.dtype

dtype('int32')

### NumPy Indexing & selection

In [145]:
import numpy as np

In [146]:
arr = np.arange(0,11)

In [148]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
arr[8]

8

In [150]:
arr[1:5]

array([1, 2, 3, 4])

In [151]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Broadcasting

Assigning a single value to multiple elements in array

Numpy arrays differ from python lists because of their ability to broadcast


In [154]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [155]:
arr[0:5] = 100

In [156]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [157]:
slice_of_arr = arr[0:6] # shares same memory location hence any changes made on one array may effect both
slice_of_arr1= arr[0:6].copy() #creates a different copy & stored in different memory location

In [158]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [160]:
slice_of_arr[0] = 200

In [161]:
slice_of_arr

array([200, 100, 100, 100, 100,   5])

In [162]:
arr

array([200, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [159]:
slice_of_arr1

array([100, 100, 100, 100, 100,   5])

In [163]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))

In [164]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [165]:
arr_2d[1]

array([20, 25, 30])

In [167]:
arr_2d[1][2:]

array([30])

In [168]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 50]])

### Pandas

Pandas is extremely powerful version of Excel
Dataframe is nothing but series 

In [4]:
import numpy as np
import pandas as pd


In [171]:
labels = ['a','b','c']
my_list = [10,20,30]

In [172]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [173]:
#series is different from numpy array i.e., series can have indexes other than integer

pd.Series(data = my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [23]:
from numpy.random import randn
import pandas as pd

In [24]:
df = pd.DataFrame(data = randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [6]:
df

W         X         Y         Z
A -0.036127 -0.208097 -0.157488 -0.731879
B -1.823735 -0.310647 -1.423711  1.396922
C -0.417217 -1.870028  0.321475 -0.898780
D  0.179599 -0.230498 -1.013324  0.944109
E  1.100577 -1.477331  1.183816  0.694108

In [7]:
df['W']

A   -0.036127
B   -1.823735
C   -0.417217
D    0.179599
E    1.100577
Name: W, dtype: float64

In [8]:
df[['W','Y']]

W         Y
A -0.036127 -0.157488
B -1.823735 -1.423711
C -0.417217  0.321475
D  0.179599 -1.013324
E  1.100577  1.183816

In [9]:
df['new'] = df['W'] + df['Y']

In [10]:
df

W         X         Y         Z       new
A -0.036127 -0.208097 -0.157488 -0.731879 -0.193615
B -1.823735 -0.310647 -1.423711  1.396922 -3.247445
C -0.417217 -1.870028  0.321475 -0.898780 -0.095742
D  0.179599 -0.230498 -1.013324  0.944109 -0.833725
E  1.100577 -1.477331  1.183816  0.694108  2.284394

In [11]:
df.drop('new', axis = 1, inplace = True)

In [12]:
df

W         X         Y         Z
A -0.036127 -0.208097 -0.157488 -0.731879
B -1.823735 -0.310647 -1.423711  1.396922
C -0.417217 -1.870028  0.321475 -0.898780
D  0.179599 -0.230498 -1.013324  0.944109
E  1.100577 -1.477331  1.183816  0.694108

In [13]:
df.drop('E', axis = 0, inplace = True)

In [14]:
df

W         X         Y         Z
A -0.036127 -0.208097 -0.157488 -0.731879
B -1.823735 -0.310647 -1.423711  1.396922
C -0.417217 -1.870028  0.321475 -0.898780
D  0.179599 -0.230498 -1.013324  0.944109

In [15]:
df.loc['A'] # using custom index

W   -0.036127
X   -0.208097
Y   -0.157488
Z   -0.731879
Name: A, dtype: float64

In [16]:
df.iloc[2] # using default index

W   -0.417217
X   -1.870028
Y    0.321475
Z   -0.898780
Name: C, dtype: float64

In [17]:
df.reset_index() # resets the index to 0,1,2,...n & adds custom index as a column to the dataframe

index         W         X         Y         Z
0     A -0.036127 -0.208097 -0.157488 -0.731879
1     B -1.823735 -0.310647 -1.423711  1.396922
2     C -0.417217 -1.870028  0.321475 -0.898780
3     D  0.179599 -0.230498 -1.013324  0.944109

In [20]:
newind = 'CA NY WY OR'.split()

In [21]:
df['states'] = newind

In [22]:
df

W         X         Y         Z states
A -0.036127 -0.208097 -0.157488 -0.731879     CA
B -1.823735 -0.310647 -1.423711  1.396922     NY
C -0.417217 -1.870028  0.321475 -0.898780     WY
D  0.179599 -0.230498 -1.013324  0.944109     OR

In [23]:
df.set_index('states',inplace = True)

#### Missing Data

In [24]:
df = pd.DataFrame({'A':[1,2,np.nan],
                 'B':[5,np.nan, np.nan],
                 'C':[1,2,3]})

#If dictionary is given to dataframe, keys would be used as columns & values would be used as rows of that column

In [25]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [26]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [27]:
#threshold=n requires atleast n NA values to be available to drop that row from dataframe 
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [28]:
df.fillna(value='fill value')

A           B  C
0         1.0         5.0  1
1         2.0  fill value  2
2  fill value  fill value  3

In [29]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

#### Group By

In [37]:
data = {'company':['goog','goog','msft','msft','fb','fb'],
       'Person':['sam','charlie','amy','vanessa','carl','sarah'],
       'sales':[200,120,340,124,243,350]}

In [38]:
df = pd.DataFrame(data)

In [39]:
df

company   Person  sales
0    goog      sam    200
1    goog  charlie    120
2    msft      amy    340
3    msft  vanessa    124
4      fb     carl    243
5      fb    sarah    350

###### Perform groupby on column & call an aggregate method 

###### Note: these aggregates occur only on numeric columns only

In [41]:
df.groupby('company').sum()

C:\Users\pavan\AppData\Local\Temp\ipykernel_17108\2170799480.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('company').sum()


sales
company       
fb         593
goog       320
msft       464

In [42]:
df.groupby('company').std()

C:\Users\pavan\AppData\Local\Temp\ipykernel_17108\2906500153.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('company').std()


sales
company            
fb        75.660426
goog      56.568542
msft     152.735065

In [43]:
df.groupby('company').mean()

C:\Users\pavan\AppData\Local\Temp\ipykernel_17108\4281651499.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('company').mean()


sales
company       
fb       296.5
goog     160.0
msft     232.0

In [44]:
df.groupby('company').min()

Person  sales
company                
fb          carl    243
goog     charlie    120
msft         amy    124

In [45]:
df.groupby('company').count()

Person  sales
company               
fb            2      2
goog          2      2
msft          2      2

In [58]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                   'B': ['B0', 'B1','B2','B3'],
                   'C':['C0','C1', 'C2','C3'],
                   'D':['D0','D1','D2','D3']},
                  index = [0,1,2,3])

In [59]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                   'B': ['B4', 'B5','B6','B7'],
                   'C':['C4','C5', 'C6','C7'],
                   'D':['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [60]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                   'B': ['B8', 'B9','B10','B11'],
                   'C':['C8','C9', 'C10','C11'],
                   'D':['D8','D9','D10','D11']},
                  index = [8,9,10,11])

In [61]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [62]:
df2


A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [63]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

##### Concatenation

In [64]:
#vertical concatination
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [65]:
#horizontal cpncatenation
pd.concat([df1,df2,df3], axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [67]:
df4 = pd.DataFrame({'key':['k0','k1','k2','k3'],
                  'A':['A0','A1','A2','A3'],
                   'B': ['B0', 'B1','B2','B3']})

df5 = pd.DataFrame({'key':['k0','k1','k2','k4'],
                  'C':['C0','C1', 'C2','C3'],
                   'D':['D0','D1','D2','D3']})

In [68]:
df4

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [69]:
df5

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k4  C3  D3

###### Whenever merge is perfomed we need to specify the type & also on which column we want to merge

In [70]:
#inner - whichever columns are common would be merged
pd.merge(df4,df5,how = 'inner', on = 'key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2

In [72]:
#left - merged based on the left dataframe
pd.merge(df4,df5,how = 'left', on = 'key')

key   A   B    C    D
0  k0  A0  B0   C0   D0
1  k1  A1  B1   C1   D1
2  k2  A2  B2   C2   D2
3  k3  A3  B3  NaN  NaN

In [73]:
#right - merged based on the right dataframe
pd.merge(df4,df5,how = 'right', on = 'key')

key    A    B   C   D
0  k0   A0   B0  C0  D0
1  k1   A1   B1  C1  D1
2  k2   A2   B2  C2  D2
3  k4  NaN  NaN  C3  D3

In [74]:
#outer - all columns from both dataframes would be merged
pd.merge(df4,df5,how = 'outer', on = 'key')

key    A    B    C    D
0  k0   A0   B0   C0   D0
1  k1   A1   B1   C1   D1
2  k2   A2   B2   C2   D2
3  k3   A3   B3  NaN  NaN
4  k4  NaN  NaN   C3   D3

#### Join 
##### left, right, inner, outer

Difference between merge & join is we dnt have to specify column, would be done based on index column

In [85]:
left = pd.DataFrame({'A':['A0','A1','A2'],
                    'B': ['B0','B1','B2']},
                   index =['K0','K1','K2'])

In [86]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [87]:
right = pd.DataFrame({'C':['C0','C2','C3'],
                    'D': ['D0','D2','D3']},
                   index =['K0','K2','K3'])

In [88]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [89]:
left.join(right, how = 'outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [90]:
left.join(right, how = 'inner')

A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

In [91]:
left.join(right, how =  'left')

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [92]:
left.join(right, how = 'right')

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

#### Operations

In [25]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2': [444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [94]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [95]:
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [97]:
#dispalys unique column in a row
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [98]:
#dispalys number of unique column in a row
df['col2'].nunique()

3

In [99]:
#how many times each value appeared in a column
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### Applying Functions

In [100]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [101]:
def times2(x):
    return x*2;

In [104]:
# we can apply function to a dataframe or a particular columns of dataframe using apply keyword 

df.apply(times2)

col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

In [105]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [107]:
#permenantly deletes the column
del df['col3']

In [108]:
df.columns

Index(['col1', 'col2'], dtype='object')

In [109]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [110]:
df.sort_values(by='col2',ascending=False) #sorting dataframe based on col2

col1  col2
2     3   666
1     2   555
0     1   444
3     4   444

In [29]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [111]:
df.isnull().sum()

col1    0
col2    0
dtype: int64

#### Data Input & output

In [112]:
#input
df = pd.read_csv('exercise/example')

In [114]:
dfnew=df

In [115]:
#output
#index false makes sure that index of dataframe is not stored as a column
dfnew.to_csv('example1.csv',index=False)

In [9]:
#palindrome

s = 'madpam'

for i in range(int((len(s))/2)):
    if(s[i] == s[-i-1]):
        i+=1
    else:
        break
    
if(i == int((len(s))/2)):
    print("palindrome")
else:
    print("not palindrome")

not palindrome


In [1]:
for num in range(10,51):
    if(num%2 == 0):
        print(num)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [8]:
f = [0,1]

for i in range(2,10):
    f.append(f[i-1] + f[i-2])
    
print(f)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [9]:
f = [0,1]

i =2
while i<10:
    f.append(f[i-1] + f[i-2])
    i +=1
    
print(f)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [18]:
for num in range(1,101):
    if(num%3 == 0) & (num %5 ==0):
        print("fizzbizz")
    elif(num%3 ==0):
        print("fizz")
    elif num%5 == 0:
        print("bizz")
    else:
        print(num)
        
        

1
2
fizz
4
bizz
fizz
7
8
fizz
bizz
11
fizz
13
14
fizzbizz
16
17
fizz
19
bizz
fizz
22
23
fizz
bizz
26
fizz
28
29
fizzbizz
31
32
fizz
34
bizz
fizz
37
38
fizz
bizz
41
fizz
43
44
fizzbizz
46
47
fizz
49
bizz
fizz
52
53
fizz
bizz
56
fizz
58
59
fizzbizz
61
62
fizz
64
bizz
fizz
67
68
fizz
bizz
71
fizz
73
74
fizzbizz
76
77
fizz
79
bizz
fizz
82
83
fizz
bizz
86
fizz
88
89
fizzbizz
91
92
fizz
94
bizz
fizz
97
98
fizz
bizz


In [2]:
for j in range(1,21):
    if(j%2 != 0):
        print(j)

1
3
5
7
9
11
13
15
17
19


In [4]:
s = 'pavani'

for i in range(len(s)):
    print(s[-i-1], end = '')

inavap

In [11]:
s = 'this is pavani'

l=s.split()
print(l)

for i in range(int(len(l)/2)):
    l[i], l[-i-1] = l[-i-1], l[i]

s = ' '.join(l)
print(s)

['this', 'is', 'pavani']
pavani is this


In [23]:
s = 'this is pavani'
freq = {'A':0,'E':0,'I':0,'O':0,'U':0}

for char in s:
    if char.upper() in freq.keys():
        freq[char.upper()] +=1
        
print(freq)

{'A': 2, 'E': 0, 'I': 3, 'O': 0, 'U': 0}


In [14]:
freq.keys()

dict_keys(['A', 'E', 'I', 'O', 'U'])

In [17]:
if 'A' in freq.keys():
    print('d')

d


In [25]:
l = [3,6,-4,0,4.5,23]

max = l[0]

for num in l:
    if num > max:
        max = num
        
print(max)

23


In [26]:
l = [3,6,-4,0,4.5,23]

min = l[0]

for num in l:
    if num < min:
        min = num
        
print(min)

-4


In [4]:
l = [3,6,23,-4,23,4.5,23]

max_num = l[0]
sec_max = l[1]

for num in l:
    if num > max_num:
        sec_max = max_num
        max_num = num
    elif num > sec_max and num != max_num:
        sec_max = num
        
print(sec_max)


6


In [6]:
l = [3,6,-4,0,4.5,23]

min_num = l[0]
sec_min = l[1]

for num in l:
    if num < min_num:
        sec_min = min_num
        min_num = num
    elif num < sec_min and num != min_num:
        sec_min = num

print(sec_min)

0


In [7]:
l = [3,6,-4,0,4.5,23]

sum_of_even = 0

for num in l:
    if num%2 == 0:
        sum_of_even += num

print(sum_of_even)

2


In [9]:
l = [3,6,-4,0,4.5,23,6,4]

o_l = []

for num in l:
    if num not in o_l:
        o_l.append(num)
        
print(o_l)

[3, 6, -4, 0, 4.5, 23, 4]


In [14]:
#a. Write a Python program to create a set of numbers and find the maximum and minimum values in the set.

n = int(input("Enter the number of integers u want to enter:"))

s = set()

for i in range(0,n):
    s.add(int(input("enter num:")))
    
print(s)

min_num = l[0]
max_num2 = l[0]

for num in l:
    if num < min_num:
        min_num = num
        
    elif num > max_num:
        max_num = num

print(min_num)

print(max_num2)

Enter the number of integers u want to enter:4
enter num:-4
enter num:0
enter num:6
enter num:9
{0, 9, -4, 6}
-4
23


In [19]:
#b. Write a Python program to remove a specific item from a set.

s = {0, 9, -4, 6,34,78,22}

num = int(input("enter num to be removed from set:"))

if num in s:
    s.discard(num)
    print(num)
else:
    print("Number not there in set")

enter num to be removed from set:24
Number not there in set


In [24]:
#c. Write a Python program to find the intersection and union of two given sets.

s1 = {0, 9, -4, 6,34,78,22}
s2 = {0, 19, -4, 6, 67,120,111}

print("Union", s1.union(s2))
print("Intersection", s1.intersection_update(s2))
print(s1)

Union {0, 34, 67, 6, 9, 78, 111, 19, 22, 120, -4}
Intersection None
{0, -4, 6}


In [ ]:
#d. Write a Python program to check if a given set is a subset of another set.

In [30]:
s1 = {0, 19, -4}
s2 = {0, 19, -4, 6, 67,120,111}


s1.issubset(s2)

True

In [31]:
#a. Write a Python program to create a dictionary with key-value pairs and print the dictionary.

n = int(input("enter num to be removed from set:"))

d = {}

for i in range(0,n):
    k = input("enter key")
    v = input("enter value")
    
    d[k] = v
    
print(d)

enter num to be removed from set:3
enter key2
enter value4
enter key3
enter value5
enter key2
enter value9
{'2': '9', '3': '5'}


In [33]:
#b. Write a Python program to remove a key from a dictionary.

d = {'2': '9', '3': '5'}
 
key = input("enter num to be removed from set:")

if key in d.keys():
    d.pop(key)
    print("deleted")
else:
    print("key not available in dict")

enter num to be removed from set:6
key not available in dict


In [46]:
#c. Write a Python program to sort a dictionary by key.

d = {'2': '9', '3': '5', '0': '6'}
o_d = {}

for key in sorted(d): o_d[key] = d[key

print(d)
print(o_d)

{'2': '9', '3': '5', '0': '6'}
{'0': '6', '2': '9', '3': '5'}


In [ ]:
#d. Write a Python program to find the value associated with a given key in a dictionary.

In [39]:
d = {'2':'9', '3': '5', '0': '6'}

key = input("enter the key")

if(key in d.keys()):
    print(d[key])
else:
    print("key not present")

enter the key3
5


In [47]:
#3) Tuples
#a. Write a Python program to create a tuple with numbers and print the first and last elements of the tuple.

t = (3,4,5,7,1,23,6,90)

print(t[0], t[len(t) - 1])

3 90


In [48]:
#b. Write a Python program to find the length of a given tuple.

print(len(t))

8


In [54]:
#c. Write a Python program to concatenate two tuples.

t1 = (8,4,5)

t + t1


(3, 4, 5, 7, 1, 23, 6, 90, 8, 4, 5)

In [55]:
#d. Write a Python program to create a tuple with elements of different data types and print each element.

t =(0,5.6,"hey")

print(t)

(0, 5.6, 'hey')


In [2]:
#a. Write a Python program to find the sum of all the elements in a given list.

l = [3,5,2]

print(sum(l))

#or
#list comprehensions

sum_of_l = sum([x for x in l])

10


In [3]:
#b. Write a Python program to remove duplicates from a list.

l = [3,3,5,2,7,5,4,8,0,1]
o_l = []

for num in l:
    if num not in o_l:
        o_l.append(num)
        
print(o_l)


[3, 5, 2, 7, 4, 8, 0, 1]


In [6]:
#c. Write a Python program to find the second largest number in a given list.

l = [3,3,5,2,7,5,4,8,0,1]
max_num = l[0]
sec_max = l[0]

for num in l:
    if num > max_num:
        sec_max = max_num
        max_num = num
    elif num > sec_max and num != max_num:
        sec_max = num

print(sec_max)


7


In [9]:
#d. Write a Python program to sort a given list in descending order.

l = [3,3,5,2,7,5,4,8,0,1]

l.sort(reverse = True)

l

[8, 7, 5, 5, 4, 3, 3, 2, 1, 0]

In [10]:
#remove duplicates
l = [3,3,5,2,7,5,4,8,0,1]
o_l = []
for num in l:
    if num % 2 == 0:
        o_l.append(num)
        
print(o_l)

[2, 4, 8, 0]


In [13]:
#character frequency
s = "this is pavani"

d = {}

for char in s:
    if char in d.keys():
        d[char] += 1
    else:
        d.update({char:1})
        
print(d)

{'t': 1, 'h': 1, 'i': 3, 's': 2, ' ': 2, 'p': 1, 'a': 2, 'v': 1, 'n': 1}


In [19]:
#output list having strings with more than 5 characters

l = ['pavani', 'pavan', 'tmh', 'billapati', '456789']

o_l = []
for s in l:
    if(len(s) > 5):
        o_l.append(s)
        
print(o_l)

['pavani', 'billapati', '456789']


In [ ]:
#output list having strings with more than 5 characters with list comprehension

o_l = [s for s in l if len(s) > 5]

print(o_l)

In [21]:
#dispaly common elements in list

l1 = ['delhi', 4, 5,12,34]
l2 = [4,19,'sry','delhi']

l1 = set(l1)
l2 = set(l2)

print(l1.intersection(l2))

{'delhi', 4}


In [25]:
#returns a new string with every other character removed

s = "this is pavani"
s1 = s[::2]
s1

'ti spvn'

In [31]:
l = [3,3,5,2,7,5,4,8,0,-1.2]

print(min(l))
print(max(l))

-1.2
8


In [37]:
s = 'madpaM'

s = s.replace(" ","").lower()

if(s == s[::-1]):
    print("Palindrome")
else:
    print("not a palindrome")

not a palindrome


In [39]:
s = 'abc'
s[::-1]

'cba'

In [40]:
l = [3,-3,5,2,-7,5,4,8,0,-1.2]

sum_of_positive = 0 

for num in l:
    if num> 0:
        sum_of_positive += num
    
    
print(sum_of_positive)

27


In [46]:
#Create a program that generates a list of 10 random integers between 1 and 100,
#then uses a break statement to exit the loop as soon as it encounters a number divisible by both 3 and 5.

import numpy as np
l = np.random.randint(1,101,10)

for num in l:
    if num % 5 == 0 & num%3 == 0:
        break
    else:
        print(num)
        continue

37
31
4
49
39


In [47]:
#uses a continue statement to skip over any vowels, then prints out the modified string without vowels.

s = 'pavani'

o = []

for char in s:
    if char.lower() in ['a','e','i','o','u']:
        continue;
    else:
        o.append(char)
        
o = "".join(o)
        
        


In [49]:
print(o)

pvn


In [50]:
while 1:
    num = np.random.randint(1,11)
    user_guess = input("enter ur guess")
    if(user_guess == num):
        print("ur guess is correct")
        break;
    else:
        continue

enter ur guess4
enter ur guess5
enter ur guess6
enter ur guess8
enter ur guess3
enter ur guess4
enter ur guess0
enter ur guess3
enter ur guess


KeyboardInterrupt: Interrupted by user

In [52]:
#lambda function to return sum of integers

sum_l = lambda a,b: a+b
    
print(sum_l(2,5))

7


In [53]:
#4) Convert the following function into a lambda function:
#def multiply(x, y): return x * y

mul = lambda x,y: x*y

print(mul(6,7))

42


In [57]:
# Create an instance of the Person class and call the introduce_yourself() method.

class Person:
    def __init__(self,name):
        self.name = name
    def introduce_yourself(self):
        print(f'hello i am {self.name}')

In [58]:
person1 = Person('pavani')
person1.introduce_yourself()

hello i am pavani


In [63]:
def sum_of_args(*args):
    sum_of_l = 0
    for num in args:
        sum_of_l +=num
    return sum_of_l   

In [64]:
sum_of_args(4,5,6)

15

In [71]:
def print_order(*args):
    for num in args:
        print(num, end = " ")

In [72]:
print_order(4,3,8)

4 3 8 

In [1]:
def highest_num(*args):
    max_num = args[0]
    for num in args:
        if num > max_num:
            max_num = num
    return max_num
highest_num(4,3,8)

8

In [2]:
def highest_num(*args):
    max_num = args[0]
    max_num = [num for num in args if num > max_num]
    return max_num
highest_num(4,3,8)

[8]

In [9]:
def merged_dict(**kwargs):
    d = {}
    for dicti in kwargs.values():
        d.update(dicti)
    return d

In [10]:
dict1 = {'k1':'v1', 'k2' : 'v2','k3':'v3'}
dict2 = {'k4':'v4','k5':'v5'}
print(merged_dict(dict1=dict1,dict2=dict2))


{'k1': 'v1', 'k2': 'v2', 'k3': 'v3', 'k4': 'v4', 'k5': 'v5'}


In [11]:
def sum_of_args_kwargs(*args,**kargs):
    sum_of_arg = 0
    for num in args:
        sum_of_arg +=num
    for num in kargs.values():
        sum_of_arg +=num
    return sum_of_arg


In [13]:
total = sum_of_args_kwargs(1,6,7, k1 =100, k2=300)
print(total)

414


In [14]:
def check(*args,**kargs):
    search_num = int(input("enter number to be searched"))
    if num in args:
        print("found")
    for num in kargs.values():
        if num == search_num:
            print("found")
            

In [21]:
check(1,6,7, a =100, b=300)

enter number to be searched4


In [26]:
def add(l,*args,**kargs):
    if len(args):
        l.extend(args)
    if len(kargs):
        l.extend(kargs.values())
    return l

In [27]:
l = [2,3,4]
print(add(l,4,9,0,a=2,b=-3))

[2, 3, 4, 4, 9, 0, 2, -3]


In [41]:
def sum_of_2_num(a,/,*,b):
    #print(a)
    total = a + b;
    return total

In [44]:
sum_of_2_num(a=4,3)

SyntaxError: positional argument follows keyword argument (2377762537.py, line 1)

In [45]:
a = 3

In [47]:
print(type(a))

<class 'int'>


In [1]:
class Person:
    def __init__(self,name):
        self.name = name
        
    #def __str__(self):
        #return f'{self.name}'        

In [4]:
p1 = Person("Pavani")

print(p1)

Pavani


In [5]:
#modify object attribute
p1.name = 'pavan'

In [6]:
print(p1)

pavan


In [7]:
#deleting object attribute

del p1.name

In [8]:
print(p1)

AttributeError: 'Person' object has no attribute 'name'

In [12]:
print(p1)

AttributeError: 'Person' object has no attribute 'name'

In [13]:
#deleting the instance

del p1

In [14]:
p1

NameError: name 'p1' is not defined

In [17]:
#Inheritance
#Parent/Base class

class Person:
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname
    
    def printname(self):
        print(self.firstname, self.lastname)

In [23]:
#Child/Derived class

class Student(Person):
    def __init__(self,fname,lname):
        #we can or not call parent class constructor in child __init__()
        #1 way of calling parent class constructor
        #Person.__init__(self,fname,lname)
        #another way of calling parent class constructor
        super().__init__(fname,lname)
        #The child's __init__() function overrides the inheritance of the parent's __init__() function.

In [24]:
x = Student("John", "Doe")

In [26]:
x.printname()

John Doe


In [31]:
#Iterator

l = [1,2,3,4,5,6,7]
my_l = iter(l)

print(next(my_l))
print(next(my_l))
print(next(my_l))
print(next(my_l))
print(next(my_l))
print(next(my_l))
print(next(my_l))

1
2
3
4
5
6
7


In [33]:
s = "Pavani"
my_s = iter(s)

for ch in s:
    print(next(my_s))

P
a
v
a
n
i


In [34]:
class MyNumbers:
    def __iter__(self):
        self.a = 1
        return self
    def __next__(self):
        if self.a <= 20:
            x = self.a
            self.a += 1
            return x
        else:
            raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [1]:
d = {1:100,2:200,3:300,4:400}

my_iter = iter(d)

for key in d.keys():
    print(d[key])


100
200
300
400


In [12]:
class myNumbers:
    def __iter__(self):
        self.a =1
        return self
    
    def __next__(self):
        x = self.a
        self.a += 1
        return x

In [13]:
num = myNumbers()

In [14]:
num.__iter__()

In [15]:
for i in range(0,10):
    print(num.__next__())

1
2
3
4
5
6
7
8
9
10


In [19]:
class myNumbers1:
    def __iter__(self):
        self.a = 1
        return self
    
    def __next__(self):
        x = self.a
        self.a += 1
        return x

In [20]:
x = myNumbers1()

In [23]:
x.__iter__()
x.__next__()

1

In [24]:
#Module is similar to code library
#It's a file containing set of functions to include in your application
#To create a module just save the code you want in a file with the file extension .py
#can be used in another program by using import

In [26]:
import datetime as dt

In [29]:
d = dt.datetime.now()
print(d)

2024-01-11 15:07:08.271772


In [30]:
print(d.year)

2024


In [31]:
print(d.day)

11


In [32]:
d.month

1

In [33]:
d.hour

15

In [34]:
d.min

datetime.datetime(1, 1, 1, 0, 0)

In [38]:
print(d.minute)

7


In [39]:
d.min #return minimum representable datetime value

datetime.datetime(1, 1, 1, 0, 0)

In [43]:
#to create date we use datetime constructor

datetime(2020,3,20,'EST')

TypeError: 'str' object cannot be interpreted as an integer

In [44]:
from datetime import datetime, timezone, timedelta

# Create a datetime object with a specific timezone offset (UTC+2 in this example)
your_datetime = datetime(2022, 1, 1, 12, 30, tzinfo=timezone(timedelta(hours=2)))

print(f"Datetime with timezone: {your_datetime}")

Datetime with timezone: 2022-01-01 12:30:00+02:00


In [45]:
d.strftime('%B')

'January'

In [46]:
min(12,4,56)

4

In [47]:
l = [23,6,3,2]

In [48]:
max(l)

23

In [49]:
abs(-4.5) #returns positive value

4.5

In [50]:
pow(3,2)

9

In [51]:
import math

math.sqrt(64)

8.0

In [52]:
math.ceil(9.2)

10

In [53]:
math.floor(9.2)

9

In [54]:
math.pi

3.141592653589793

In [55]:
x = '{ "name":"John", "age":30, "city":"New York"}'

In [57]:
import json
y = json.loads(x)

In [58]:
y["name"]

'John'

In [59]:
x = {
  "name": "John",
  "age": 30,
  "city": "New York"
}

In [60]:
#convert to json
y = json.dumps(x)

In [61]:
print(y)

{"name": "John", "age": 30, "city": "New York"}


In [62]:
print(json.dumps({"name": "John", "age": 30}))
print(json.dumps(["apple", "bananas"]))
print(json.dumps(("apple", "bananas")))
print(json.dumps("hello"))
print(json.dumps(42))
print(json.dumps(31.76))
print(json.dumps(True))
print(json.dumps(False))
print(json.dumps(None))

{"name": "John", "age": 30}
["apple", "bananas"]
["apple", "bananas"]
"hello"
42
31.76
true
false
null


In [64]:
x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}

In [65]:
# use four indents to make it easier to read the result:
print(json.dumps(x))

{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cars": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.1}]}


In [67]:
print(json.dumps(x, indent=4))

{
    "name": "John",
    "age": 30,
    "married": true,
    "divorced": false,
    "children": [
        "Ann",
        "Billy"
    ],
    "pets": null,
    "cars": [
        {
            "model": "BMW 230",
            "mpg": 27.5
        },
        {
            "model": "Ford Edge",
            "mpg": 24.1
        }
    ]
}


In [68]:
# use . and a space to separate objects, and a space, a = and a space to separate keys from their values:
print(json.dumps(x, indent=4, separators=(". ", " = ")))

{
    "name" = "John". 
    "age" = 30. 
    "married" = true. 
    "divorced" = false. 
    "children" = [
        "Ann". 
        "Billy"
    ]. 
    "pets" = null. 
    "cars" = [
        {
            "model" = "BMW 230". 
            "mpg" = 27.5
        }. 
        {
            "model" = "Ford Edge". 
            "mpg" = 24.1
        }
    ]
}


In [69]:
# sort the result alphabetically by keys:
print(json.dumps(x, indent=4, sort_keys=True))

{
    "age": 30,
    "cars": [
        {
            "model": "BMW 230",
            "mpg": 27.5
        },
        {
            "model": "Ford Edge",
            "mpg": 24.1
        }
    ],
    "children": [
        "Ann",
        "Billy"
    ],
    "divorced": false,
    "married": true,
    "name": "John",
    "pets": null
}
